---
environment:
    PY3MODS: cookiecutter cffi pycotap pydistman pysol_cards pytest pytest-cov random2 six tox tox-appveyor wheel
    TOXENV: py312
    TOX_APPVEYOR_X64: "1"
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
# The image specification may be required by python3.12 on MS Windows:
# https://www.appveyor.com/docs/lang/python/
image:
    - Visual Studio 2019
install:
    # - pkg-config --version
    - choco install strawberryperl
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PATH=C:\Python312-x64;%PATH%
    - python3 --version
    - python3 -m pip install %PY3MODS%
    - perl -v
    - if not exist C:\Perl5 mkdir C:\Perl5
    - SET PATH=C:\msys64\bin;C:\Perl5\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PERL5LIB=C:/Perl5/lib/perl5
    - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
    - SET PERL_MB_OPT=--install_base C:/Perl5
    - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
    - cpanm --notest Code::TidyAll::Plugin::ClangFormat Code::TidyAll::Plugin::TestCount Dir::Manifest Dist::Zilla Env::Path Games::Solitaire::Verify::Solution IO::All Inline Inline::C Path::Tiny~0.146 Perl::Critic Perl::Tidy Pod::Coverage::TrustPod Pod::Weaver::Section::Support String::ShellQuote Test::CPAN::Changes Test::Code::TidyAll Test::Differences Test::EOL Test::Kwalitee Test::NoTabs Test::Pod Test::Pod::Coverage Test::RunValgrind Test::Some Test::TrailingSpace Test::Trap
build: off
test_script:
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - set TOXENV=py312
    - set bhslibdir=%HOME%\apps\fcs\lib
    - SET PATH=%PATH%;%bhslibdir%
    - set bhslibdir2=%HOME%\apps\fcs\bin
    - SET PATH=%PATH%;%bhslibdir2%
    - perl black-hole-solitaire/CI-testing/continuous-integration-testing.pl --disable-embedded-python --gen="MSYS Makefiles" --skip-pypi
shallow_clone: true
