=encoding utf8

=head1 NAME

black-hole-solve - Utility for solving Golf Solitaire, Black Hole Solitaire,
and All in a Row Solitaire games.

=head1 SYNOPSIS

black-hole-solve B<--game> [golf|black_hole|all_in_a_row] /path/to/board.txt

=head1 DESCRIPTION

B<black-hole-solve> is a command line application that solves a single deal
of Golf Solitaire, Black Hole Solitaire, or All in a Row Solitaire.

Also provided is a C library with an API.

=head1 OPTIONS

See B<--help> .

B<TODO> B<FILL_IN>

=head1 EXAMPLE

    $ make_pysol_freecell_board.py -F -t 24 black_hole | \
        black-hole-solve --game black_hole -

=head1 SEE ALSO

B<make_pysol_freecell_board.py>(6)

=head1 AUTHOR

Shlomi Fish, L<http://www.shlomifish.org/> .

=cut
